export const GET_TOKEN = 'GET_TOKEN'
export const GET_REFRESH_TOKEN = 'GET_REFRESH_TOKEN'
export const GET_TOKEN_MINUTES_REMAINING = 'GET_TOKEN_MINUTES_REMAINING'
export const GET_CURRENT_PROCESSING = 'GET_CURRENT_PROCESSING'

export const GET_QUEUE = 'GET_QUEUE'
export const GET_PROCESSING = 'GET_PROCESSING'
export const GET_IS_CANCELLED = 'GET_IS_CANCELLED'