export const SET_USER_PROFILE = 'SET_USER_PROFILE'
export const SET_USER_TOKEN = 'SET_USER_TOKEN'
export const UPDATE_USER_TOKEN = 'UPDATE_USER_TOKEN'
export const REFRESH_USER_TOKEN = 'REFRESH_USER_TOKEN'
export const LOG_USER_OUT = 'LOG_USER_OUT'

export const ADD_JOB_TO_QUEUE = 'ADD_JOB_TO_QUEUE'
export const CHECK_FOR_JOB = 'CHECK_FOR_JOB'
